### ISSUE TITLE
Melhorias no código

### ISSUE THREAD

**Issue by arthurs159** [FelipeSdsilva/productCatalog#1]
Ei Felipe, olhando o projeto, consigo identificar uma serie de melhorias no código, coisa simples, mas deixaria o código mais limpo, vou listar aqui em baixo.

Nessa parte do código, acredito que dê para você utilizar o method reference do java onde você  utiliza o map `(x) -> new ProviderDTO(x)`, deixando muito mais simples o código, Depois de alguma atualização do java, hoje é possível apenas da o `toList()` sem utilizar o `collectors`
![image](https://user-images.githubusercontent.com/77133022/200133696-63c8749e-c1fc-4491-839f-8ba36d7ef315.png)

==

Nessa parte do código, você conseguiria fazer o optional apenas em uma linha, ja dando o `.orElseThrow` logo após o `findById`
![image](https://user-images.githubusercontent.com/77133022/200133777-7b0ba9ff-783a-4819-91ac-ba4665528307.png)

==

Essa dica é mais preferencia minha mesmo, então se quiser seguir, deixo à seu criterio, os seus `convertEntityToDto`, acredito que seja melhor deixar o metodo dentro da propria entidade, deixando essa responsabilidade por lá, saca? O que acha da ideia?
![image](https://user-images.githubusercontent.com/77133022/200133899-dca8d974-1b93-4fd0-a881-8ef298ee2ba8.png)

Essas dias servem para todos os seus services, caso queira melhora-los. ; )

**Comment by FelipeSdsilva** [comment]
Bom muito obrigao novamente pelas ideias e vou acatar sim, eu não estava tão por dentro dessas atualizações no Jacva muito obrigado e vou arrumar sim com muito carinho, 

Agradeço seu tempo e disponibilidade gostei muito da sua issue bem explicativa.
